sudo: false
before_script:
- mkdir /home/travis/bin
- curl -L https://github.com/yihui/ubuntu-bin/releases/download/latest/pandoc.tar.gz
  | tar xvz -C /home/travis/bin
- export PATH="$PATH:/home/travis/bin"
script: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  make &&
  pip install --user ghp-import &&
  ghp-import -n out &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
addons:
  apt:
    packages:
    - texlive-full
env:
  global:
    secure: bHfqf8RFQwYGWTYaGo5j+LOl+wBfs13espkUNVC7mxhlh41dfrb5/S5Tq2e5vyQlnO0bVF65bFJefG+li2bwwvvQ06U+CIZp/IkK4fnXML7zlAfyHC5786IDPPB+lFRvs2YT5LKDjY7r7R2ZbdeItKcYvJGGkME57xGpU/dqt4/RDkAUBGVhKwo0vXDhh1+7D5C7YJBNp+LNUSs7hIsBAz+Ap/M/wyV82InTSvy2cqLFl7xl3HqdVPj2vrmVuTIUyn64qmEPE9dJawPZYxpYNA6CWWmdO7eRotQOvVbDb7+UqcwGy4cII9QCF1YNPpq8L2LALgj1umt3x2x/o/49k4SCMHAPQ6SfmbZJPL+nS4+v4uM6i/nOouKkvqX1j5ehSRLIQqGCm2YuCHv3Eb2Z4Cxj3AmJhrFhMQMm8u9S0E6VvIJ3cZAoE3ZabMeIZvMhZ2B6KCDChVfqPcCkb+jN0lSWhdUnHpqAK5XDtqOfs3mBDco5sFsKTkdQHy8ErNb0pK6a3nezjRCc2nWEyWDFVvkCYMxyngsiRD6xtnfIORbZGU4LlnAAUsfOzBW8wpprbXvxWX/7WyeO4VNFkO4f6HtUZj7Z3jFEGArVeQndttRbrwPOvVdREd+gT5SbyNEmxUwzveqvYIc/D1jUXHDXjes6RxfBBsce7x/5beWicao=
notifications:
  slack:
    secure: qLgXT9nN6sSgoQUNS5QEYeGrSXn8NWeSrw5A46HbyWskp6Rl2NaZK9YbIhl5fnsJhZj5lI76UM073ShepwSFuPtDkeVZ0v4dgwjTyyO+Oi+J56JjVkGqeK1mLA+p/AutrIcUXrKDHsKiRyCGxdexEa3yXoQGdhqkNmgLjL7tn3JkJwt8nuFcBsAw8W1hFeSUiY1iC2NgZNmsJAobhucaA4Jd/f1+yJEXnp/o33mONcbKeZrE1JbhEBrLjxg30MHb8LcdI1b5r8SzxQaMxBVhj1Bjd0TDjiPeeU3RkoKX38V3qDubiHLk0k/KepLuDRx04XKxWNywS5ju+LKiQoIRYhPGr/QibNjY+vzfKskU2whfMjGLw/IYPQaWVlvP3pZ47hmpI58OwhHGT48HyrWeFuOcdr2EPYmDuNdTCoZZ733j8Q1kVNuIlIr7qF9TDTz8OelUq/d3c1kvlpOs7L5d7YBh04g/s+25vvJc82CpQVd2cQmVvsZOYtPq3UQhpgwf/VTxQ/B3n7GUbftR0tejxHCjoAPK6esU7zWT840ytGQoAxr/0OnJMTzo77A74xw7sD+tWI9BzftMZHYVOxlYPoSJoznF2ik96s6S/pGA/Af1W+1s0nTPKmxVQcRXDBGgHoTHJVFd+0ryEpO0TQRIa/6bv5JkIiBBnYTtI6OBiFA=
